### ISSUE TITLE
Compilation error when migrating from 4.3.0 to 5.0.0

### ISSUE THREAD

**Issue by perissf1** [sumup/sumup-android-sdk#221]
When migrating the dependancy to sumup sdk, I get this compilation error:

> Task :app:hiltJavaCompileDebug FAILED
error: ComponentProcessingStep was unable to process 'com.perissf.xyz.MyApplication_HiltComponents.SingletonC' because 'net.openid.appauth.AuthorizationService' could not be resolved.
  
  Dependency trace:
      => element (CLASS): com.sumup.identity.auth.implementation.di.HiltAuthModule.Companion
      => element (METHOD): provideAuthorizationService(android.content.Context)
      => type (EXECUTABLE method): (android.content.Context)net.openid.appauth.AuthorizationService
ComponentProcessingStep was unable to process 'com.perissf.xyz.MyApplication_HiltComponents.SingletonC' because 'net.openid.appauth.AuthorizationService' could not be resolved.

      => type (ERROR return type): net.openid.appauth.AuthorizationService
  
  If type 'net.openid.appauth.AuthorizationService' is a generated type, check above for compilation errors that may have prevented the type from being generated. Otherwise, ensure that type 'net.openid.appauth.AuthorizationService' is on your classpath.
1 error

**Comment by NAVAZ-tech** [comment]
I also having the same issues,  how did you fix that let me know please

**Comment by perissf1** [comment]
Fixed by adding `net.openid:appauth` library implementation to my module's build.gradle.ktx file:

*libs.versions.toml*

    [versions]
    appauth = "0.11.1"
    [libraries]
    appauth = { module = "net.openid:appauth", version.ref = "appauth" }

*build.gradle.ktx*

        implementation(libs.appauth)

**Comment by NAVAZ-tech** [comment]
Thank you, for your solution..., now it's working, 
but i get this error 
`Execution failed for task ':app:processStagingDebugMainManifest'.
> Manifest merger failed : Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <appAuthRedirectScheme> is provided.`
I don't know why is error, if you know the solution, can you please help me to solve this
